export const departments = [
  "Department of Behavioral Sciences",
  "Department of Educational Development",
  "Department of Linguistics & Literature",
  "Department of Business Management",
  "Department of Economics",
  "Department of International Relations",
  "Department of Media and Communication",
  "Department of Agriculture and Food Technology",
  "Department of Animal Sciences",
  "Department of Chemistry",
  "Department of Environmental Sciences",
  "Department of Computer Science",
  "Department of Earth Sciences",
  "Department of Mathematical Science",
  "Department of Physics",
  "Department of Mining Engineering",
  "Department of Urdu and Regional Languages",
  "Department of Civil Engineering & Technology",
  "Department of Forestry",
  "Department of Sociology and Anthropology",
  "Department of Psychology and Human Development",
  "Medical Lab Technology (Dept. Biology)",
  "Department of Plant Science",
  "Department of Electrical Engineering",
  "Department of Biological Science",
  "Department of Open & Distance Learning",
  "Department of Sports Sciences and Physical Education",
];

export const semesters = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
];
export const programs = ["BS", "MS"];
